// Data for UVS Vacuum Pumps & Systems product series
const vacuumPumpsAndSystems = [
  {
    id: "UVS-IVP-SERIES",
    sequence: 1,
    code: "IVP-SERIES",
    name: "IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    title: "IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    description:
      "The IVP-Series consists of high-quality, belt-driven rotary vane vacuum pumps designed for reliability and industrial-grade performance. They are characterized by a compact, rugged design and high vacuum efficiency with low power and oil consumption.",
    features: [
      "Precision manufacturing with CNC machining and NC grinding for perfect sealing and interchangeability.",
      "Durable construction using specially graded cast iron vanes machined to close tolerances.",
      "Low noise and vibration operation with a low vacuum oil charge.",
      "Cartridge-type design for fast on-site serviceability with no internal or external leakage.",
      "Optional intake port with anti-suckback mechanism for improved safety.",
      "Capable of achieving ultimate vacuum levels below 1×10⁻³ mbar.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/UVS IVP series vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVP-100",
        displacement50Hz: "100 LPM",
        displacementM3hr: "6 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "25 mm",
        exhaustPort: 'PF3/4"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.3 L",
        weightPump: "28 kg",
        weightWithMotor: "45 kg",
      },
      {
        model: "IVP-180",
        displacement50Hz: "180 LPM",
        displacementM3hr: "10.8 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.8 L",
        weightPump: "32 kg",
        weightWithMotor: "50 kg",
      },
      {
        model: "IVP-300",
        displacement50Hz: "300 LPM",
        displacementM3hr: "18 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "2.2 L",
        weightPump: "35 kg",
        weightWithMotor: "60 kg",
      },
      {
        model: "IVP-600",
        displacement50Hz: "600 LPM",
        displacementM3hr: "36 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "46 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "4 L",
        weightPump: "51 kg",
        weightWithMotor: "80 kg",
      },
      {
        model: "IVP-1000",
        displacement50Hz: "1000 LPM",
        displacementM3hr: "60 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "50 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "1.5 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "6 L",
        weightPump: "105 kg",
        weightWithMotor: "130 kg",
      },
    ],
    dimensions: [
      {
        model: "IVP 100",
        A: "463",
        B: "250",
        C: "285",
        D: "425",
        E: "175",
        F: "25",
        G: "30",
        H: "20",
        I: "122",
        J: "73",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 180",
        A: "488",
        B: "285",
        C: "342",
        D: "450",
        E: "200",
        F: "32",
        G: "35",
        H: "25",
        I: "135",
        J: "88",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 300",
        A: "545",
        B: "310",
        C: "365",
        D: "515",
        E: "275",
        F: "32",
        G: "40",
        H: "30",
        I: "145",
        J: "100",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 600",
        A: "610",
        B: "350",
        C: "424",
        D: "580",
        E: "310",
        F: "46",
        G: "50",
        H: "35",
        I: "171",
        J: "110",
        K: "210",
        L: "13",
      },
      {
        model: "IVP 1.0K",
        A: "640",
        B: "420",
        C: "504",
        D: "610",
        E: "340",
        F: "49.5",
        G: "59",
        H: "40.5",
        I: "192",
        J: "130",
        K: "219",
        L: "13",
      },
    ],
    end: "This series is used across electrical, metallurgy, chemical & pharma, food processing, HVAC, and specialty applications such as jewellery casting and oil treatment.",
  },
  {
    id: "UVS-IVPVP-SERIES",
    sequence: 2,
    code: "IVPVP-SERIES",
    name: "IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    title: "IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    description:
      "The IVPVP-Series consists of two-stage rotary piston vacuum pumps designed for high-capacity industrial applications with consistent ultimate vacuum performance.",
    features: [
      "Two-stage rotary piston design for high displacement and industrial reliability.",
      "Capacity range from 1800 LPM to 9000 LPM.",
      "Ultimate vacuum level of 5×10⁻³ mbar.",
      "Water-cooled design for stable continuous operation.",
      "Heavy-duty construction suited for metallurgy, electrical, chemical, and manufacturing environments.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/UVS IVPVP Piston vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVPVP-1.8K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "63 mm",
        exhaustPort: "50 mm",
        motorPower: "4.0 kW (3 ph)",
        coolingWater: "1.7 LPM",
        weightPump: "28 kg",
        weightWithMotor: "380 kg",
      },
      {
        model: "IVPVP-4.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "80 mm",
        exhaustPort: "50 mm",
        motorPower: "7.5 kW (3 ph)",
        coolingWater: "2.5 LPM",
        weightPump: "32 kg",
        weightWithMotor: "710 kg",
      },
      {
        model: "IVPVP-7.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "11.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "35 kg",
        weightWithMotor: "960 kg",
      },
      {
        model: "IVPVP-9.0K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "15.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "51 kg",
        weightWithMotor: "1020 kg",
      },
    ],
    applications: [
      "Metallurgy: vacuum furnaces, large-scale casting, and degassing.",
      "Electrical: transformer oil purification and impregnation.",
      "Chemical & Pharma: bulk distillation, evaporation, and solvent extraction.",
      "Manufacturing: vapor absorption machines and lamp production.",
    ],
    end: "The IVPVP-Series is built for heavy-duty industrial use where high displacement, water cooling, and reliable ultimate vacuum levels are mandatory.",
  },
  {
    id: "UVS-IVPVP-ALTERNATE",
    sequence: 3,
    code: "IVPVP-PISTON-ALT",
    name: "IVPVP Piston Vacuum Pumps Brochure",
    title: "UVS IVPVP Piston Vacuum Pumps Brochure",
    description:
      "A second UVS IVPVP piston vacuum pump brochure. Use this entry when you need the alternate pump family or updated document version.",
    features: [
      "Alternate brochure for the UVS IVPVP piston vacuum pump series.",
      "May contain additional model ranges, dimension data, or cooling requirements.",
      "Use the PDF for detailed technical comparison and selection.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/UVS IVPVP Piston vacuum pumps (1).pdf",
  },
];

// Make the data globally accessible
window.vacuumPumpsAndSystems = vacuumPumpsAndSystems;
