// Data for UVS Vacuum Pumps & Systems product series
const vacuumPumpsAndSystems = [
  {
    id: "UVS-IVP-SERIES",
    sequence: 1,
    code: "IVP-SERIES",
    name: "IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    title: "IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    description:
      "The IVP-Series consists of high-quality, belt-driven rotary vane vacuum pumps designed for reliability and industrial-grade performance. They are characterized by a compact, rugged design and high vacuum efficiency with low power and oil consumption.",
    features: [
      "Precision manufacturing with CNC machining and NC grinding for perfect sealing and interchangeability.",
      "Durable construction using specially graded cast iron vanes machined to close tolerances.",
      "Low noise and vibration operation with a low vacuum oil charge.",
      "Cartridge-type design for fast on-site serviceability with no internal or external leakage.",
      "Optional intake port with anti-suckback mechanism for improved safety.",
      "Capable of achieving ultimate vacuum levels below 1×10⁻³ mbar.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVP series vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVP-100",
        displacement50Hz: "100 LPM",
        displacementM3hr: "6 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "25 mm",
        exhaustPort: 'PF3/4"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.3 L",
        weightPump: "28 kg",
        weightWithMotor: "45 kg",
      },
      {
        model: "IVP-180",
        displacement50Hz: "180 LPM",
        displacementM3hr: "10.8 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.8 L",
        weightPump: "32 kg",
        weightWithMotor: "50 kg",
      },
      {
        model: "IVP-300",
        displacement50Hz: "300 LPM",
        displacementM3hr: "18 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "2.2 L",
        weightPump: "35 kg",
        weightWithMotor: "60 kg",
      },
      {
        model: "IVP-600",
        displacement50Hz: "600 LPM",
        displacementM3hr: "36 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "46 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "4 L",
        weightPump: "51 kg",
        weightWithMotor: "80 kg",
      },
      {
        model: "IVP-1000",
        displacement50Hz: "1000 LPM",
        displacementM3hr: "60 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "50 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "1.5 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "6 L",
        weightPump: "105 kg",
        weightWithMotor: "130 kg",
      },
    ],
    dimensions: [
      {
        model: "IVP 100",
        A: "463",
        B: "250",
        C: "285",
        D: "425",
        E: "175",
        F: "25",
        G: "30",
        H: "20",
        I: "122",
        J: "73",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 180",
        A: "488",
        B: "285",
        C: "342",
        D: "450",
        E: "200",
        F: "32",
        G: "35",
        H: "25",
        I: "135",
        J: "88",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 300",
        A: "545",
        B: "310",
        C: "365",
        D: "515",
        E: "275",
        F: "32",
        G: "40",
        H: "30",
        I: "145",
        J: "100",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 600",
        A: "610",
        B: "350",
        C: "424",
        D: "580",
        E: "310",
        F: "46",
        G: "50",
        H: "35",
        I: "171",
        J: "110",
        K: "210",
        L: "13",
      },
      {
        model: "IVP 1.0K",
        A: "640",
        B: "420",
        C: "504",
        D: "610",
        E: "340",
        F: "49.5",
        G: "59",
        H: "40.5",
        I: "192",
        J: "130",
        K: "219",
        L: "13",
      },
    ],
    end: "This series is used across electrical, metallurgy, chemical & pharma, food processing, HVAC, and specialty applications such as jewellery casting and oil treatment.",
  },
  {
    id: "UVS-IVPVP-SERIES",
    sequence: 2,
    code: "IVPVP-SERIES",
    name: "IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    title: "IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    description:
      "The IVPVP-Series consists of two-stage rotary piston vacuum pumps designed for high-capacity industrial applications with consistent ultimate vacuum performance.",
    features: [
      "Two-stage rotary piston design for high displacement and industrial reliability.",
      "Capacity range from 1800 LPM to 9000 LPM.",
      "Ultimate vacuum level of 5×10⁻³ mbar.",
      "Water-cooled design for stable continuous operation.",
      "Heavy-duty construction suited for metallurgy, electrical, chemical, and manufacturing environments.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVPVP Piston vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVPVP-1.8K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "63 mm",
        exhaustPort: "50 mm",
        motorPower: "4.0 kW (3 ph)",
        coolingWater: "1.7 LPM",
        weightPump: "28 kg",
        weightWithMotor: "380 kg",
      },
      {
        model: "IVPVP-4.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "80 mm",
        exhaustPort: "50 mm",
        motorPower: "7.5 kW (3 ph)",
        coolingWater: "2.5 LPM",
        weightPump: "32 kg",
        weightWithMotor: "710 kg",
      },
      {
        model: "IVPVP-7.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "11.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "35 kg",
        weightWithMotor: "960 kg",
      },
      {
        model: "IVPVP-9.0K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "15.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "51 kg",
        weightWithMotor: "1020 kg",
      },
    ],
    applications: [
      "Metallurgy: vacuum furnaces, large-scale casting, and degassing.",
      "Electrical: transformer oil purification and impregnation.",
      "Chemical & Pharma: bulk distillation, evaporation, and solvent extraction.",
      "Manufacturing: vapor absorption machines and lamp production.",
    ],
    end: "The IVPVP-Series is built for heavy-duty industrial use where high displacement, water cooling, and reliable ultimate vacuum levels are mandatory.",
  },
  {
    id: "UVS-IVPVP-ALTERNATE",
    sequence: 3,
    code: "IVPVP-PISTON-ALT",
    name: "IVPVP Piston Vacuum Pumps Brochure",
    title: "UVS IVPVP Piston Vacuum Pumps Brochure",
    description:
      "A second UVS IVPVP piston vacuum pump brochure. Use this entry when you need the alternate pump family or updated document version.",
    features: [
      "Alternate brochure for the UVS IVPVP piston vacuum pump series.",
      "May contain additional model ranges, dimension data, or cooling requirements.",
      "Use the PDF for detailed technical comparison and selection.",
    ],
    images: ["./assests/img/Mask3.png"],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVPVP Piston vacuum pumps (1).pdf",
  },
  {
    id: "UVS-ROTARY-ROOTS",
    sequence: 4,
    code: "ROTARY-ROOTS-SYSTEMS",
    name: "Rotary Roots Pumping Systems",
    title: "Two Stage Rotary With Roots Vacuum Pumping Systems",
    description:
      "Over the years, Unique Vacuum Solutions has expertised in delivering efficient and effective vacuum pumping systems for various industrial applications. These systems integrate two-stage rotary pumps with roots blowers for high-capacity evacuation.",
    features: [
      "Designed for Cryo lines, cryo cans, and cryo cylinders evacuation.",
      "Capacity range: 1000 LPM Rotary (250 m³/hr roots) to 2000 LPM Rotary (550 m³/hr roots).",
      "Ultimate vacuum: 1×10⁻⁴ mbar.",
      "Includes liquid nitrogen trap and inline valves.",
      "Individual line vacuum measurement for precision monitoring.",
      "High-performance integrated roots blower for enhanced displacement.",
    ],
    modelVariants: [
      {
        model: "1000 LPM System",
        rotaryPumpCapacity: "1000 LPM",
        rootsBlowerCapacity: "250 m³/hr",
        ultimateVacuum: "1×10⁻⁴ mbar",
        applications: "Cryo lines, Cryo cans",
      },
      {
        model: "2000 LPM System",
        rotaryPumpCapacity: "2000 LPM",
        rootsBlowerCapacity: "550 m³/hr",
        ultimateVacuum: "1×10⁻⁴ mbar",
        applications: "Cryo cylinders evacuation",
      },
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/IMG_7133-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/IMG_7246-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/KGWB0060-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/LXKO7545-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/vacuumepumps&System.png",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/UVS ROTARY ROOTS PUMPING SYSTEMS.docx",
    end: "These systems are specifically configured for demanding cryogenics and industrial applications requiring reliable high-capacity vacuum performance.",
  },
  {
    id: "UVS-TURBO-PUMPING",
    sequence: 5,
    code: "TURBO-PUMPING-SYSTEMS",
    name: "Turbo Pumping Systems",
    title: "Turbo High Vacuum Pumping Systems",
    description:
      "Over the years, Unique Vacuum Solutions has expertised in delivering efficient and effective high-vacuum Turbo pumping systems for various industrial applications. These systems are designed for high performance, reliability, and precision vacuum control.",
    features: [
      "Integrated with high-vacuum measurement instruments and gauges.",
      "Fore & Rough pump options: from 100 LPM to 1000 LPM.",
      "Turbo pump options: from 60 LPS to 2000 LPS.",
      "Ultimate vacuum: better than 10⁻⁷ mbar.",
      "Fully automated single button operation or semi-automatic options.",
      "Total assembly mounted on a robust mild steel / stainless steel cart.",
      "Equipped with roughing/backing valves and evacuation port monitoring.",
    ],
    modelVariants: [
      {
        model: "Standard Turbo Cart",
        foreRoughPumpRange: "100 LPM to 1000 LPM",
        turboPumpRange: "60 LPS to 2000 LPS",
        ultimateVacuum: "Better than 10⁻⁷ mbar",
        mounting: "Mild Steel / Stainless Steel Cart",
        operation: "Fully Automated / Semi-Automatic",
      },
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/TURBO PUMPING SYSTEMS/UPS-250T 004.jpg",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/TURBO PUMPING SYSTEMS/UVS TURBO PUMPING SYSTEMS.docx",
    end: "These turbo pumping systems are ideal for applications requiring clean, ultra-high vacuum environments with integrated monitoring and control instrumentation.",
  },
  {
    id: "UVS-DIFFUSION-PUMPING",
    sequence: 6,
    code: "DIFFUSION-PUMPING-SYSTEMS",
    name: "Diffusion Pumping Systems",
    title: "High Vacuum Standard Pumping Systems",
    description:
      "Vacuum Pumping systems are the most reliable and cost-effective means for producing high vacuum. The vacuum pumping systems are trolley mounted for easy movement and capable of achieving an ultimate vacuum of 10⁻⁶ mbar with Liquid nitrogen trap. UVS offers many choices of vacuum pumping systems, with different pumping speeds for various applications, ranging from USP-65D to UPS-300F and custom-built solutions.",
    features: [
      "Setting the desired vacuum and single button operation to achieve at the port.",
      "Vacuum range from 10⁻² to 10⁻⁶ mbar.",
      "Auto change over from roughing mode to high vacuum mode.",
      "Auto closure of cycle with load port isolation.",
      "Fully automatic pumps start with all the safety interlocks.",
      "Complete cycle monitoring on the HMI screen.",
      "Data logging of total evacuation cycle.",
    ],
    modelVariants: [
      {
        model: "UPS-100D",
        diffusionPump: "OD-114D diffstak 280LPS (un baffled)",
        rotaryPumpModel: "URP-15",
        speedLitMin: "280 LPM",
        highVacuumValveSize: "QSV-4",
        roughingBackingValves: "QSV-1 – 2nos.",
        ultimateVacuum: ">1.0E-6 mbar (with Ln2 trap)",
        inletCollarDiameter: "114mm",
        powerRequired: "230 V - 50Hz, 1 Phase, 10 A",
        coolingWater: "2 ltr/min at 25°C",
      },
    ],
    applications: [
      "Metallurgy and high-vacuum furnaces.",
      "Industrial coating and thin-film deposition.",
      "Laboratory research and high-vacuum experiments.",
      "Custom built solutions for specialized vacuum applications.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/IMG_7135.JPG",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/IMG_7088.JPG",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/HIGH VACUUM STANDARD PUMPING SYSTEMS.docx",
    end: "The standard Vacuum Pumping Systems consists of UVS Rotary Vacuum Pump, Diffusion pumps and other hardware like valves, baffles, collar, gauge and plumbing lines with Pirani Gauge to measure the roughing and backing vacuum & Penning gauge for measuring the high vacuum.",
  },
];

// Make the data globally accessible
window.vacuumPumpsAndSystems = vacuumPumpsAndSystems;
