// Data for UVS Vacuum Pumps & Systems product series
const vacuumPumpsAndSystems = [
  {
    id: "UVS-IVP-SERIES",
    sequence: 1,
    code: "IVP-SERIES",
    name: "UVS IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    title: "UVS IVP-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    description:
      "The IVP-Series consists of high-quality, belt-driven rotary vane vacuum pumps designed for reliability and industrial-grade performance. They are characterized by a compact, rugged design and high vacuum efficiency with low power and oil consumption.",
    features: [
      "Precision manufacturing with CNC machining and NC grinding for perfect sealing and interchangeability.",
      "Durable construction using specially graded cast iron vanes machined to close tolerances.",
      "Low noise and vibration operation with a low vacuum oil charge.",
      "Cartridge-type design for fast on-site serviceability with no internal or external leakage.",
      "Optional intake port with anti-suckback mechanism for improved safety.",
      "Capable of achieving ultimate vacuum levels below 1×10⁻³ mbar.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/ivp1.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/ivp2.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVP series vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVP-100",
        displacement50Hz: "100 LPM",
        displacementM3hr: "6 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "25 mm",
        exhaustPort: 'PF3/4"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.3 L",
        weightPump: "28 kg",
        weightWithMotor: "45 kg",
      },
      {
        model: "IVP-180",
        displacement50Hz: "180 LPM",
        displacementM3hr: "10.8 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.8 L",
        weightPump: "32 kg",
        weightWithMotor: "50 kg",
      },
      {
        model: "IVP-300",
        displacement50Hz: "300 LPM",
        displacementM3hr: "18 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "2.2 L",
        weightPump: "35 kg",
        weightWithMotor: "60 kg",
      },
      {
        model: "IVP-600",
        displacement50Hz: "600 LPM",
        displacementM3hr: "36 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "46 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "4 L",
        weightPump: "51 kg",
        weightWithMotor: "80 kg",
      },
      {
        model: "IVP-1000",
        displacement50Hz: "1000 LPM",
        displacementM3hr: "60 m³/hr",
        ultimatePressureGasBallast: "<1×10⁻² torr",
        ultimatePressureNoGasBallast: "<1×10⁻³ torr",
        inletPort: "50 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "1.5 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "6 L",
        weightPump: "105 kg",
        weightWithMotor: "130 kg",
      },
    ],
    dimensions: [
      {
        model: "IVP 100",
        A: "463",
        B: "250",
        C: "285",
        D: "425",
        E: "175",
        F: "25",
        G: "30",
        H: "20",
        I: "122",
        J: "73",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 180",
        A: "488",
        B: "285",
        C: "342",
        D: "450",
        E: "200",
        F: "32",
        G: "35",
        H: "25",
        I: "135",
        J: "88",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 300",
        A: "545",
        B: "310",
        C: "365",
        D: "515",
        E: "275",
        F: "32",
        G: "40",
        H: "30",
        I: "145",
        J: "100",
        K: "171",
        L: "13",
      },
      {
        model: "IVP 600",
        A: "610",
        B: "350",
        C: "424",
        D: "580",
        E: "310",
        F: "46",
        G: "50",
        H: "35",
        I: "171",
        J: "110",
        K: "210",
        L: "13",
      },
      {
        model: "IVP 1.0K",
        A: "640",
        B: "420",
        C: "504",
        D: "610",
        E: "340",
        F: "49.5",
        G: "59",
        H: "40.5",
        I: "192",
        J: "130",
        K: "219",
        L: "13",
      },
    ],
    end: "This series is used across electrical, metallurgy, chemical & pharma, food processing, HVAC, and specialty applications such as jewellery casting and oil treatment.",
  },
  {
    id: "UVS-IVPVP-SERIES",
    sequence: 2,
    code: "IVPVP-SERIES",
    name: "UVS IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    title: "UVS IVPVP-Series Two Stage Rotary Piston Vacuum Pump",
    description:
      "The IVPVP-Series consists of two-stage rotary piston vacuum pumps designed for high-capacity industrial applications with consistent ultimate vacuum performance.",
    features: [
      "Two-stage rotary piston design for high displacement and industrial reliability.",
      "Capacity range from 1800 LPM to 9000 LPM.",
      "Ultimate vacuum level of 5×10⁻³ mbar.",
      "Water-cooled design for stable continuous operation.",
      "Heavy-duty construction suited for metallurgy, electrical, chemical, and manufacturing environments.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVPVP_2.png",
       "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVPVP_1.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVPVP Piston vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVPVP-1.8K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "63 mm",
        exhaustPort: "50 mm",
        motorPower: "4.0 kW (3 ph)",
        coolingWater: "1.7 LPM",
        weightPump: "28 kg",
        weightWithMotor: "380 kg",
      },
      {
        model: "IVPVP-4.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "80 mm",
        exhaustPort: "50 mm",
        motorPower: "7.5 kW (3 ph)",
        coolingWater: "2.5 LPM",
        weightPump: "32 kg",
        weightWithMotor: "710 kg",
      },
      {
        model: "IVPVP-7.2K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "11.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "35 kg",
        weightWithMotor: "960 kg",
      },
      {
        model: "IVPVP-9.0K",
        ultimatePressure: "5×10⁻³ torr",
        inletPort: "100 mm",
        exhaustPort: "80 mm",
        motorPower: "15.0 kW (3 ph)",
        coolingWater: "3.5 LPM",
        weightPump: "51 kg",
        weightWithMotor: "1020 kg",
      },
    ],
    applications: [
      "Metallurgy: vacuum furnaces, large-scale casting, and degassing.",
      "Electrical: transformer oil purification and impregnation.",
      "Chemical & Pharma: bulk distillation, evaporation, and solvent extraction.",
      "Manufacturing: vapor absorption machines and lamp production.",
    ],
    end: "The IVPVP-Series is built for heavy-duty industrial use where high displacement, water cooling, and reliable ultimate vacuum levels are mandatory.",
  },
  {
    id: "UVS-E-SERIES",
    sequence: 3,
    code: "E-SERIES",
    name: "UVS E-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    title: "UVS E-Series Oil Sealed Belt Drive Rotary Vane Vacuum Pump",
    description:
      "The E-Series consists of high-quality, belt-driven rotary vane vacuum pumps designed for reliability and industrial-grade performance. They are characterized by a compact, rugged design and high vacuum efficiency with low power and oil consumption.",
    features: [
      "High quality reliable pump, economically priced.",
      "Advanced compact rugged design.",
      "Light weight, offers high degree of vacuum with lower consumption of power & oil.",
      "Components manufactured on high precision CNC machining center and NC grinding machine ensure perfect sealing and 100% interchangeability of parts.",
      "Specially graded cast Iron vanes machined to very close tolerances ensure high vacuum levels.",
      "Low noise and vibration levels with low vacuum oil charge.",
      "No internal / external leakage.",
      "Cartridge type design enabling easy and fast serviceability at site.",
      "Intake port with anti-suckback mechanism (optional).",
      "Ready availability of spares, backed by nationwide efficient after sales service.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/E1.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/E2.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/OIL SEALED BELT DRIVE ROTARY VANE VACUUM PUMP.pdf",
    modelVariants: [
      {
        model: "E-100",
        displacement50Hz: "100 LPM",
        displacementM3hr: "6 m³/hr",
        ultimatePressureGasBallast: "<5×10⁻² torr",
        ultimatePressureNoGasBallast: "<5×10⁻³ torr",
        inletPort: "25 mm",
        exhaustPort: 'PF3/4"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.3 L",
        weightPump: "28 kg",
        weightWithMotor: "45 kg",
      },
      {
        model: "E-180",
        displacement50Hz: "180 LPM",
        displacementM3hr: "10.8 m³/hr",
        ultimatePressureGasBallast: "<5×10⁻² torr",
        ultimatePressureNoGasBallast: "<5×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.4 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "1.8 L",
        weightPump: "32 kg",
        weightWithMotor: "50 kg",
      },
      {
        model: "E-300",
        displacement50Hz: "300 LPM",
        displacementM3hr: "18 m³/hr",
        ultimatePressureGasBallast: "<5×10⁻² torr",
        ultimatePressureNoGasBallast: "<5×10⁻³ torr",
        inletPort: "32 mm",
        exhaustPort: 'PF1"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "2.2 L",
        weightPump: "35 kg",
        weightWithMotor: "60 kg",
      },
      {
        model: "E-600",
        displacement50Hz: "600 LPM",
        displacementM3hr: "36 m³/hr",
        ultimatePressureGasBallast: "<5×10⁻² torr",
        ultimatePressureNoGasBallast: "<5×10⁻³ torr",
        inletPort: "46 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "0.75 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "4 L",
        weightPump: "51 kg",
        weightWithMotor: "80 kg",
      },
      {
        model: "E-1000",
        displacement50Hz: "1000 LPM",
        displacementM3hr: "60 m³/hr",
        ultimatePressureGasBallast: "<5×10⁻² torr",
        ultimatePressureNoGasBallast: "<5×10⁻³ torr",
        inletPort: "50 mm",
        exhaustPort: 'PF1 1/2"',
        motorPower: "1.5 kW",
        rotationalSpeed: "600 RPM",
        oilCapacity: "6 L",
        weightPump: "105 kg",
        weightWithMotor: "130 kg",
      },
    ],
    dimensions: [
      {
        model: "WSVP-E 100",
        A: "463",
        B: "250",
        C: "285",
        D: "425",
        E: "175",
        F: "25",
        G: "30",
        H: "20",
        I: "122",
        J: "73",
        K: "171",
        L: "13",
      },
      {
        model: "WSVP-E 180",
        A: "488",
        B: "285",
        C: "342",
        D: "450",
        E: "200",
        F: "32",
        G: "35",
        H: "25",
        I: "135",
        J: "88",
        K: "171",
        L: "13",
      },
      {
        model: "WSVP-E 300",
        A: "545",
        B: "310",
        C: "365",
        D: "515",
        E: "275",
        F: "32",
        G: "40",
        H: "30",
        I: "145",
        J: "100",
        K: "171",
        L: "13",
      },
      {
        model: "WSVP-E 600",
        A: "610",
        B: "350",
        C: "424",
        D: "580",
        E: "310",
        F: "46",
        G: "50",
        H: "35",
        I: "171",
        J: "110",
        K: "210",
        L: "13",
      },
      {
        model: "WSVP-E 1000",
        A: "640",
        B: "420",
        C: "504",
        D: "610",
        E: "340",
        F: "49.5",
        G: "59",
        H: "40.5",
        I: "192",
        J: "130",
        K: "219",
        L: "13",
      },
    ],
    applications: [
      "Electrical Industry: Transformer oil purification, Impregnation, Capacitor.",
      "Metallurgy: Vacuum Furnace, Degassing, Casting.",
      "Chemical / Pharma / Food Industry: Drying, Distillation, Evaporation, Solvent Extraction, Degassing.",
      "Refrigeration & Air conditioning.",
      "Vapour Absorption Machines.",
      "Lamp Manufacturing: GS, TL, CFL.",
      "Oil Treatment.",
      "Jewellery Casting.",
    ],
    end: "The E-Series is built for reliability in demanding industrial environments where performance and efficiency are key.",
  },
  {
    id: "UVS-ROTARY-ROOTS",
    sequence: 4,
    code: "ROTARY-ROOTS-SYSTEMS",
    name: "Rotary Roots Pumping Systems",
    title: "Two Stage Rotary With Roots Vacuum Pumping Systems",
    description:
      "Over the years, Unique Vacuum Solutions has expertised in delivering efficient and effective vacuum pumping systems for various industrial applications. These systems integrate two-stage rotary pumps with roots blowers for high-capacity evacuation.",
    features: [
      "Designed for Cryo lines, cryo cans, and cryo cylinders evacuation.",
      "Capacity range: 1000 LPM Rotary (250 m³/hr roots) to 2000 LPM Rotary (550 m³/hr roots).",
      "Ultimate vacuum: 1×10⁻⁴ mbar.",
      "Includes liquid nitrogen trap and inline valves.",
      "Individual line vacuum measurement for precision monitoring.",
      "High-performance integrated roots blower for enhanced displacement.",
    ],
    modelVariants: [
      {
        model: "1000 LPM System",
        rotaryPumpCapacity: "1000 LPM",
        rootsBlowerCapacity: "250 m³/hr",
        ultimateVacuum: "1×10⁻⁴ mbar",
        applications: "Cryo lines, Cryo cans",
      },
      {
        model: "2000 LPM System",
        rotaryPumpCapacity: "2000 LPM",
        rootsBlowerCapacity: "550 m³/hr",
        ultimateVacuum: "1×10⁻⁴ mbar",
        applications: "Cryo cylinders evacuation",
      },
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/IMG_7133-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/IMG_7246-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/KGWB0060-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/LXKO7545-removebg.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/vacuumepumps&System.png",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/ROTARY ROOTS/UVS ROTARY ROOTS PUMPING SYSTEMS.pdf",
    end: "These systems are specifically configured for demanding cryogenics and industrial applications requiring reliable high-capacity vacuum performance.",
  },
  {
    id: "UVS-TURBO-PUMPING",
    sequence: 5,
    code: "TURBO-PUMPING-SYSTEMS",
    name: "Turbo Pumping Systems",
    title: "Turbo High Vacuum Pumping Systems",
    description:
      "Over the years, Unique Vacuum Solutions has expertised in delivering efficient and effective high-vacuum Turbo pumping systems for various industrial applications. These systems are designed for high performance, reliability, and precision vacuum control.",
    features: [
      "Integrated with high-vacuum measurement instruments and gauges.",
      "Fore & Rough pump options: from 100 LPM to 1000 LPM.",
      "Turbo pump options: from 60 LPS to 2000 LPS.",
      "Ultimate vacuum: better than 10⁻⁷ mbar.",
      "Fully automated single button operation or semi-automatic options.",
      "Total assembly mounted on a robust mild steel / stainless steel cart.",
      "Equipped with roughing/backing valves and evacuation port monitoring.",
    ],
    modelVariants: [
      {
        model: "Standard Turbo Cart",
        foreRoughPumpRange: "100 LPM to 1000 LPM",
        turboPumpRange: "60 LPS to 2000 LPS",
        ultimateVacuum: "Better than 10⁻⁷ mbar",
        mounting: "Mild Steel / Stainless Steel Cart",
        operation: "Fully Automated / Semi-Automatic",
      },
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/TURBO PUMPING SYSTEMS/UPS-250T 004.jpg",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/TURBO PUMPING SYSTEMS/vertex TMP system.jpg",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/TURBO PUMPING SYSTEMS/UVS TURBO PUMPING SYSTEMS.pdf",
    end: "These turbo pumping systems are ideal for applications requiring clean, ultra-high vacuum environments with integrated monitoring and control instrumentation.",
  },
  {
    id: "UVS-DIFFUSION-PUMPING",
    sequence: 6,
    code: "DIFFUSION-PUMPING-SYSTEMS",
    name: "Diffusion Pumping Systems",
    title: "High Vacuum Standard Pumping Systems",
    description:
      "Vacuum Pumping systems are the most reliable and cost-effective means for producing high vacuum. The vacuum pumping systems are trolley mounted for easy movement and capable of achieving an ultimate vacuum of 10⁻⁶ mbar with Liquid nitrogen trap. UVS offers many choices of vacuum pumping systems, with different pumping speeds for various applications, ranging from USP-65D to UPS-300F and custom-built solutions.",
    features: [
      "Setting the desired vacuum and single button operation to achieve at the port.",
      "Vacuum range from 10⁻² to 10⁻⁶ mbar.",
      "Auto change over from roughing mode to high vacuum mode.",
      "Auto closure of cycle with load port isolation.",
      "Fully automatic pumps start with all the safety interlocks.",
      "Complete cycle monitoring on the HMI screen.",
      "Data logging of total evacuation cycle.",
    ],
    modelVariants: [
      {
        model: "UPS-100D",
        diffusionPump: "OD-114D diffstak 280LPS (un baffled)",
        rotaryPumpModel: "URP-15",
        speedLitMin: "280 LPM",
        highVacuumValveSize: "QSV-4",
        roughingBackingValves: "QSV-1 – 2nos.",
        ultimateVacuum: ">1.0E-6 mbar (with Ln2 trap)",
        inletCollarDiameter: "114mm",
        powerRequired: "230 V - 50Hz, 1 Phase, 10 A",
        coolingWater: "2 ltr/min at 25°C",
      },
    ],
    applications: [
      "Metallurgy and high-vacuum furnaces.",
      "Industrial coating and thin-film deposition.",
      "Laboratory research and high-vacuum experiments.",
      "Custom built solutions for specialized vacuum applications.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/IMG_7135.JPG",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/IMG_7088.JPG",
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/DIFFUSION PUMPING SYSTEMS/HIGH VACUUM STANDARD PUMPING SYSTEMS.pdf",
    end: "The standard Vacuum Pumping Systems consists of UVS Rotary Vacuum Pump, Diffusion pumps and other hardware like valves, baffles, collar, gauge and plumbing lines with Pirani Gauge to measure the roughing and backing vacuum & Penning gauge for measuring the high vacuum.",
  },
  {
    id: "UVS-CENTRALIZED-VACUUM-SYSTEM",
    sequence: 6.5,
    code: "CENTRALIZED-VACUUM-SYSTEMS",
    name: "Centralized Vacuum Systems",
    title: "Centralized Vacuum Systems",
    description:
      "UVS Centralized Vacuum Systems are high-performance vacuum networks designed for automated and custom pressure regulation across facilities. Available in both Multi-Vacuum and Single-Vacuum configurations, these systems feature advanced setpoint controllers, complete automatic operations, manual override controls, and integrated suction and exhaust oil mist eliminator (OME) filters to ensure clean, efficient, and continuous industrial vacuum supply.",
    features: [
      "Multi-pump staging: dynamically cycles pumps based on target setpoints (rough, medium, fine vacuum levels).",
      "Automatic control: completely automated operation with manual control override facilities.",
      "Integrated filtration: comes standard with high-efficiency suction and exhaust OME filters.",
      "Custom setpoints: up to three different vacuum level controllers linked to specific pump configurations.",
      "High reliability: robust centralized design reduces maintenance overhead and optimizes power consumption."
    ],
    modelVariants: [
      {
        model: "Multi Vacuum Level Control System",
        capacity: "3200 Lpm",
        ultimateVacuum: "1×10⁻³ Mbar",
        controlLevels: "3 Different Setpoints",
        operation: "Automatic & Manual Override",
        filters: "Suction & Exhaust OME Filters"
      },
      {
        model: "Single Vacuum Level Control System",
        capacity: "2000 Lpm",
        ultimateVacuum: "1×10⁻³ Mbar",
        controlLevels: "Single Setpoint",
        operation: "Automatic & Manual Override",
        filters: "Suction & Exhaust OME Filters"
      }
    ],
    applications: [
      "Hospital & Medical Centralized Vacuum Systems",
      "Industrial Manufacturing & Automated Assembly Lines",
      "Laboratory and R&D Central Vacuum Networks",
      "Woodworking, CNC Routing, and Vacuum Clamping Systems",
      "Packaging, Canning, and Bottling Operations"
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_3.jpg",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_4.jpg",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_5.jpg",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_7.jpg",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_2.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/extracted_img_1_6.jpg"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPING SYSTEMS/CENTRALISEDVACUUMPUMPINGSYSTEMS/UVS CENTRALISED VACUUM SYSTEMS.pdf",
    end: "UVS Centralized Vacuum Systems are engineered to deliver precise vacuum control. In multi-level systems, the controllers systematically scale operation: rough vacuum runs one pump set, medium runs two sets, and fine vacuum activates all three sets automatically to meet the peak demand level.",
  },
  {
    id: "UVS-IVRVP-M-SERIES",
    sequence: 7,
    code: "IVRVP-M-SERIES",
    name: "IVRVP-M Series Roots - Air Cooled Vacuum Pumps",
    title: " UVS ROOTS - AIR COOLED VACUUM PUMPS",
    description:
      "The IVRVP-M Series consists of air-cooled roots vacuum pumps designed for high-capacity industrial applications requiring efficient displacement and reliable ultimate vacuum performance. These pumps are robustly built for continuous operation in demanding environments.",
    features: [
      "Air-cooled design for simplified installation and maintenance.",
      "High displacement capacity ranging from 550 m³/hr to 9000 m³/hr.",
      "Achieves an ultimate vacuum level of 7×10⁻⁴ mbar.",
      "Robust construction suitable for heavy-duty industrial vacuum systems.",
      "Energy-efficient performance across a wide range of models.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRVP-M-SERIES.png"
    ],
    // pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRVP-M - MAGNETIC ROOTS VACUUM PUMPS.pdf",
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS-IVRVP-M-SERIES.pdf",
    modelVariants: [
      {
        model: "IVRRP 550",
        displacement: "540 m3/hr",
        ultimatePressure: "7X10⁻⁴ Torr",
        inletPort: "100 mm",
        exhaustPort: "100 mm",
        motorPower: "2.2 kW",
        weight: "220 kg",
        cooling: "Air",
      },
      {
        model: "IVRRP 1100",
        displacement: "1080 m3/hr",
        ultimatePressure: "7X10⁻⁴ Torr",
        inletPort: "150 mm",
        exhaustPort: "150 mm",
        motorPower: "4.0 kW",
        weight: "310 kg",
        cooling: "Air",
      },
      {
        model: "IVRRP 2200",
        displacement: "2160 m3/hr",
        ultimatePressure: "7X10⁻⁴ Torr",
        inletPort: "200 mm",
        exhaustPort: "200 mm",
        motorPower: "7.5 kW",
        weight: "630 kg",
        cooling: "Air",
      },
      {
        model: "IVRRP 4400",
        displacement: "4322 m3/hr",
        ultimatePressure: "7X10⁻⁴ Torr",
        inletPort: "250 mm",
        exhaustPort: "250 mm",
        motorPower: "11.0 kW",
        weight: "815 kg",
        cooling: "Air",
      },
      {
        model: "IVRRP 9000",
        displacement: "9000 m3/hr",
        ultimatePressure: "7X10⁻⁴ Torr",
        inletPort: "320 mm",
        exhaustPort: "320 mm",
        motorPower: "18.5 kW",
        weight: "1350 kg",
        cooling: "Air",
      },
    ],
  },
  {
    id: "UVS-IVRVP-SERIES",
    sequence: 8,
    code: "IVRVP-SERIES",
    name: "IVRVP Series Roots - Water Cooled Vacuum Pumps",
    title: "UVS ROOTS - WATER COOLED VACUUM PUMPS",
    description:
      "The IVRVP Series consists of water-cooled roots vacuum pumps designed for high-performance industrial applications. These pumps offer efficient displacement and stable ultimate vacuum levels, with a water-cooled design ensuring reliable continuous operation even in demanding thermal conditions.",
    features: [
      "Water-cooled design for enhanced thermal stability and continuous operation.",
      "Displacement capacity ranging from 250 m³/hr to 9000 m³/hr.",
      "Ultimate vacuum level better than 4×10⁻⁴ mbar.",
      "Robust construction for heavy-duty industrial vacuum processing.",
      "High efficiency and reliable performance for metallurgy, chemical, and industrial applications.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRVP-SERIES.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRVP- Roots(water cooled).pdf",
    modelVariants: [
      {
        model: "IVRRP 250",
        displacement: "250 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "80 mm",
        exhaustPort: "80 mm",
        motorPower: "1.1 kW",
        weight: "110 kg",
        cooling: "Water",
      },
      {
        model: "IVRRP 550",
        displacement: "540 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "100 mm",
        exhaustPort: "100 mm",
        motorPower: "2.2 kW",
        weight: "190 kg",
        cooling: "Water",
      },
      {
        model: "IVRRP 1100",
        displacement: "1080 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "150 mm",
        exhaustPort: "150 mm",
        motorPower: "4.0 kW",
        weight: "265 kg",
        cooling: "Water",
      },
      {
        model: "IVRRP 2200",
        displacement: "2160 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "200 mm",
        exhaustPort: "200 mm",
        motorPower: "7.5 kW",
        weight: "570 kg",
        cooling: "Water",
      },
      {
        model: "IVRRP 4400",
        displacement: "4322 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "250 mm",
        exhaustPort: "250 mm",
        motorPower: "11.0 kW",
        weight: "770 kg",
        cooling: "Water",
      },
      {
        model: "IVRRP 9000",
        displacement: "9000 m3/hr",
        ultimatePressure: "4x10⁻⁴ Torr",
        inletPort: "320 mm",
        exhaustPort: "320 mm",
        motorPower: "18.5 kW",
        weight: "1350 kg",
        cooling: "Water",
      },
    ],
  },
  {
    id: "UVS-IVRDP-SERIES",
    sequence: 9,
    code: "IVRDP-SERIES",
    name: "IVRDP Series Two Stage Rotary Vane Vacuum Pump",
    title: "UVS TWO STAGE ROTARY VANE VACUUM PUMP",
    description:
      "The IVRDP Series consists of high-performance two-stage rotary vane vacuum pumps designed for reliability and efficiency in various industrial processes. These pumps feature dual protection against oil anti-sucking back, a forced oil circulation system for stable running, and are built with fewer components for easy maintenance.",
    features: [
      "High ultimate vacuum performance (< 4×10⁻⁴ mbar).",
      "Two-shift adjustable gas ballast valve for handling condensable vapors like water vapor.",
      "Dual protection against oil anti-sucking back to prevent oil flowback upon stopping.",
      "Forced oil circulation system with a constant pressure oil supply for stable operation.",
      "Simplified design with fewer components for easier maintenance and repair.",
      "Extremely low noise levels and low operating temperatures.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRDP- SERIES1.png",
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRDP- SERIES2.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVRDP- two stage rotary vane.pdf",
    modelVariants: [
      {
        model: "IVRDP-4",
        displacementLPM: "66 LPM",
        displacementM3hr: "6 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF16/25 (PF3/4\")",
        motorPower: "0.4 kW",
        rotationalSpeed: "1440 RPM",
        oilCapacity: "1.3 L",
        weight: "19 kg",
        noiseLevel: "≤56 dB",
      },
      {
        model: "IVRDP-8",
        displacementLPM: "132 LPM",
        displacementM3hr: "10.8 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF16/25 (PF1\")",
        motorPower: "0.4 kW",
        rotationalSpeed: "1440 RPM",
        oilCapacity: "1.8 L",
        weight: "21 kg",
        noiseLevel: "≤56 dB",
      },
      {
        model: "IVRDP-16",
        displacementLPM: "264 LPM",
        displacementM3hr: "18 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF25 (PF1\")",
        motorPower: "0.75 kW",
        rotationalSpeed: "1440 RPM",
        oilCapacity: "2.2 L",
        weight: "30 kg",
        noiseLevel: "≤58 dB",
      },
      {
        model: "IVRDP-24",
        displacementLPM: "396 LPM",
        displacementM3hr: "36 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF25/40 (PF1 1/2\")",
        motorPower: "0.75 kW",
        rotationalSpeed: "1440 RPM",
        oilCapacity: "4 L",
        weight: "35 kg",
        noiseLevel: "≤58 dB",
      },
      {
        model: "IVRDP-30",
        displacementLPM: "498 LPM",
        displacementM3hr: "60 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF25/40 (PF1 1/2\")",
        motorPower: "1.1 kW",
        rotationalSpeed: "1440 RPM",
        oilCapacity: "6 L",
        weight: "43 kg",
        noiseLevel: "≤58 dB",
      },
      {
        model: "IVRDP-48",
        displacementLPM: "798 LPM",
        displacementM3hr: "48 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF40",
        motorPower: "1.5 kW",
        rotationalSpeed: "1440 RPM",
        weight: "62 kg",
        noiseLevel: "≤62 dB",
      },
      {
        model: "IVRDP-65",
        displacementLPM: "1080 LPM",
        displacementM3hr: "65 m³/hr",
        ultimatePressureWithGasBallast: "5×10⁻³ mbar",
        ultimatePressureWithoutGasBallast: "5×10⁻⁴ mbar",
        inletExhaustPort: "KF40",
        motorPower: "2.2 kW",
        rotationalSpeed: "1440 RPM",
        weight: "65 kg",
        noiseLevel: "≤62 dB",
      },
    ],
    dimensions: [
      { model: "IVRDP-4", A: "460", B: "144", C: "207", D: "210", E: "110", G: "126", H: "154", I: "45", J: "45", K: "34", L: "/", DN: "KF-16/25" },
      { model: "IVRDP-8", A: "460", B: "144", C: "207", D: "210", E: "110", G: "126", H: "154", I: "45", J: "45", K: "34", L: "/", DN: "KF-16/25" },
      { model: "IVRDP-16", A: "520", B: "188", C: "272", D: "320", E: "148", G: "160", H: "165", I: "69", J: "59", K: "38", L: "295", DN: "KF25" },
      { model: "IVRDP-24", A: "560", B: "188", C: "272", D: "320", E: "148", G: "160", H: "185", I: "82", J: "59", K: "47", L: "295", DN: "KF25/40" },
      { model: "IVRDP-30", A: "560", B: "188", C: "272", D: "320", E: "148", G: "160", H: "185", I: "82", J: "59", K: "47", L: "295", DN: "KF25/40" },
      { model: "IVRDP-48", A: "730", B: "234", C: "358", D: "396", E: "190", G: "200", H: "223", I: "157", J: "69", K: "55", L: "390", DN: "KF40" },
      { model: "IVRDP-65", A: "730", B: "234", C: "358", D: "396", E: "190", G: "200", H: "223", I: "157", J: "69", K: "55", L: "390", DN: "KF40" },
    ],
  },
  {
    id: "UVS-IVSVP-SERIES",
    sequence: 10,
    code: "IVSVP-SERIES",
    name: "IVSVP Series Single Stage Vacuum Pump",
    title: "UVS IVSVP Single Stage Vacuum Pumps",
    description:
      "Vacuum technology plays a critical role in the industrial field. The IVSVP Series is designed to meet the most demanding customer requirements, offering high reliability, efficient pumping of condensable gases, and a design that prevents oil exhaust or leakage, ensuring no emulsification of pump oil.",
    features: [
      "Integrated anti-sucking back valve for system protection.",
      "Multiple shift gas ballast design for versatile vapor evacuation.",
      "German-made oil seals to effectively prevent leakage.",
      "High-quality oil mist filters for clean exhaust and longer service life.",
      "Compact and robust design for various industrial applications.",
      "Integral exhaust filter (discharge air 99% oil-free).",
      "Extremely low noise and operating temperatures.",
    ],
    images: [
      "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/IVSVP.png"
    ],
    pdf: "./assests/img/products/VacuumePumpsAndSystem/VACUUM PUMPS/UVS IVSVP - Single stage vacuum pumps.pdf",
    modelVariants: [
      {
        model: "IVSVP-020",
        displacement: "20 m³/h",
        ultimatePressureWithoutGasBallast: "/",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "/",
        noiseLevel: "≤65 dB",
        powerRating: "0.75 kW",
        motorSpeed: "3000 rpm",
        oilCapacity: "0.5 L",
        weight: "19.5 kg",
      },
      {
        model: "IVSVP-028",
        displacement: "28 m³/h",
        ultimatePressureWithoutGasBallast: "≤0.1 mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤58 dB",
        powerRating: "1.1 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "1 L",
        weight: "30 kg",
      },
      {
        model: "IVSVP-040",
        displacement: "40 m³/h",
        ultimatePressureWithoutGasBallast: "≤0.1 mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤59 dB",
        powerRating: "1.1 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "2 L",
        weight: "39.2 kg",
      },
      {
        model: "IVSVP-065",
        displacement: "65 m³/h",
        ultimatePressureWithoutGasBallast: "≤0.1 mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤61 dB",
        powerRating: "1.5 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "2 L",
        weight: "42.5 kg",
      },
      {
        model: "IVSVP-100",
        displacement: "100 m³/h",
        ultimatePressureWithoutGasBallast: "≤0.1 mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤62 dB",
        powerRating: "2.2 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "2 L",
        weight: "72 kg",
      },
      {
        model: "IVSVP-160",
        displacement: "160 m³/h",
        ultimatePressureWithoutGasBallast: "≤8x10⁻² mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤70 dB",
        powerRating: "4 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "5~7 L",
        weight: "132 kg",
      },
      {
        model: "IVSVP-200",
        displacement: "200 m³/h",
        ultimatePressureWithoutGasBallast: "≤8x10⁻² mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤70 dB",
        powerRating: "4 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "5~7 L",
        weight: "132 kg",
      },
      {
        model: "IVSVP-300",
        displacement: "300 m³/h",
        ultimatePressureWithoutGasBallast: "≤8x10⁻² mbar",
        ultimatePressureWithGasBallast1: "≤0.5 mbar",
        ultimatePressureWithGasBallast2: "≤1.5 mbar",
        noiseLevel: "≤71 dB",
        powerRating: "5.5 kW",
        motorSpeed: "1440 rpm",
        oilCapacity: "7~9 L",
        weight: "205 kg",
      },
    ],
  },
];

// Make the data globally accessible
window.vacuumPumpsAndSystems = vacuumPumpsAndSystems;
